{"date":"Wed Jul 12 2023 13:23:54 GMT+0530 (India Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: someting failed miserably!\nError: someting failed miserably!\n    at Object.<anonymous> (C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly\\index.js:26:7)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","os":{"loadavg":[0,0,0],"uptime":560266.125},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly\\index.js"],"cwd":"C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":54206289,"external":55138054,"heapTotal":64532480,"heapUsed":35756224,"rss":90185728},"pid":5156,"uid":null,"version":"v18.14.2"},"stack":"Error: someting failed miserably!\n    at Object.<anonymous> (C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly\\index.js:26:7)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","trace":[{"column":7,"file":"C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly\\index.js","function":null,"line":26,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1254,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1308,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1117,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":958,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":23,"method":null,"native":false}]}
{"date":"Wed Jul 12 2023 13:25:48 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"level":"error","message":"uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"someting failed \".\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"someting failed \".","os":{"loadavg":[0,0,0],"uptime":560380.015},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly\\index.js"],"cwd":"C:\\Users\\vrind\\Desktop\\Web Dev\\node\\vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":54206289,"external":55157149,"heapTotal":64270336,"heapUsed":35775328,"rss":90943488},"pid":17156,"uid":null,"version":"v18.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"someting failed \".","trace":[]}
